// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessageWithEnum.proto

package io.confluent.connect.protobuf.test;

public final class TestMessageWithEnumWrapper {
  private TestMessageWithEnumWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestMessageWithEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMessageWithEnum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
     * @return The enum numeric value on the wire for enumField.
     */
    int getEnumFieldValue();
    /**
     * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
     * @return The enumField.
     */
    io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType getEnumField();

    /**
     * <code>string stringField = 2;</code>
     * @return The stringField.
     */
    java.lang.String getStringField();
    /**
     * <code>string stringField = 2;</code>
     * @return The bytes for stringField.
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();

    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     * @return Whether the nullableInt32Field field is set.
     */
    boolean hasNullableInt32Field();
    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     * @return The nullableInt32Field.
     */
    com.google.protobuf.Int32Value getNullableInt32Field();
    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getNullableInt32FieldOrBuilder();
  }
  /**
   * Protobuf type {@code TestMessageWithEnum}
   */
  public static final class TestMessageWithEnum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMessageWithEnum)
      TestMessageWithEnumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestMessageWithEnum.newBuilder() to construct.
    private TestMessageWithEnum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMessageWithEnum() {
      enumField_ = 0;
      stringField_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestMessageWithEnum();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessageWithEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              enumField_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stringField_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (nullableInt32Field_ != null) {
                subBuilder = nullableInt32Field_.toBuilder();
              }
              nullableInt32Field_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nullableInt32Field_);
                nullableInt32Field_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.internal_static_TestMessageWithEnum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.internal_static_TestMessageWithEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.class, io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.Builder.class);
    }

    /**
     * Protobuf enum {@code TestMessageWithEnum.EnumType}
     */
    public enum EnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>A = 0;</code>
       */
      A(0),
      /**
       * <code>B = 1;</code>
       */
      B(1),
      /**
       * <code>C = 2;</code>
       */
      C(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>A = 0;</code>
       */
      public static final int A_VALUE = 0;
      /**
       * <code>B = 1;</code>
       */
      public static final int B_VALUE = 1;
      /**
       * <code>C = 2;</code>
       */
      public static final int C_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EnumType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EnumType forNumber(int value) {
        switch (value) {
          case 0: return A;
          case 1: return B;
          case 2: return C;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnumType>() {
              public EnumType findValueByNumber(int number) {
                return EnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnumType[] VALUES = values();

      public static EnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TestMessageWithEnum.EnumType)
    }

    public static final int ENUMFIELD_FIELD_NUMBER = 1;
    private int enumField_;
    /**
     * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
     * @return The enum numeric value on the wire for enumField.
     */
    @java.lang.Override public int getEnumFieldValue() {
      return enumField_;
    }
    /**
     * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
     * @return The enumField.
     */
    @java.lang.Override public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType getEnumField() {
      @SuppressWarnings("deprecation")
      io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType result = io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.valueOf(enumField_);
      return result == null ? io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.UNRECOGNIZED : result;
    }

    public static final int STRINGFIELD_FIELD_NUMBER = 2;
    private volatile java.lang.Object stringField_;
    /**
     * <code>string stringField = 2;</code>
     * @return The stringField.
     */
    @java.lang.Override
    public java.lang.String getStringField() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField_ = s;
        return s;
      }
    }
    /**
     * <code>string stringField = 2;</code>
     * @return The bytes for stringField.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NULLABLEINT32FIELD_FIELD_NUMBER = 3;
    private com.google.protobuf.Int32Value nullableInt32Field_;
    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     * @return Whether the nullableInt32Field field is set.
     */
    @java.lang.Override
    public boolean hasNullableInt32Field() {
      return nullableInt32Field_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     * @return The nullableInt32Field.
     */
    @java.lang.Override
    public com.google.protobuf.Int32Value getNullableInt32Field() {
      return nullableInt32Field_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : nullableInt32Field_;
    }
    /**
     * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Int32ValueOrBuilder getNullableInt32FieldOrBuilder() {
      return getNullableInt32Field();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enumField_ != io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.A.getNumber()) {
        output.writeEnum(1, enumField_);
      }
      if (!getStringFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringField_);
      }
      if (nullableInt32Field_ != null) {
        output.writeMessage(3, getNullableInt32Field());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enumField_ != io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.A.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, enumField_);
      }
      if (!getStringFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringField_);
      }
      if (nullableInt32Field_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getNullableInt32Field());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum)) {
        return super.equals(obj);
      }
      io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum other = (io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum) obj;

      if (enumField_ != other.enumField_) return false;
      if (!getStringField()
          .equals(other.getStringField())) return false;
      if (hasNullableInt32Field() != other.hasNullableInt32Field()) return false;
      if (hasNullableInt32Field()) {
        if (!getNullableInt32Field()
            .equals(other.getNullableInt32Field())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENUMFIELD_FIELD_NUMBER;
      hash = (53 * hash) + enumField_;
      hash = (37 * hash) + STRINGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getStringField().hashCode();
      if (hasNullableInt32Field()) {
        hash = (37 * hash) + NULLABLEINT32FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getNullableInt32Field().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestMessageWithEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMessageWithEnum)
        io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.internal_static_TestMessageWithEnum_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.internal_static_TestMessageWithEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.class, io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.Builder.class);
      }

      // Construct using io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        enumField_ = 0;

        stringField_ = "";

        if (nullableInt32FieldBuilder_ == null) {
          nullableInt32Field_ = null;
        } else {
          nullableInt32Field_ = null;
          nullableInt32FieldBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.internal_static_TestMessageWithEnum_descriptor;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum getDefaultInstanceForType() {
        return io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum build() {
        io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum buildPartial() {
        io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum result = new io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum(this);
        result.enumField_ = enumField_;
        result.stringField_ = stringField_;
        if (nullableInt32FieldBuilder_ == null) {
          result.nullableInt32Field_ = nullableInt32Field_;
        } else {
          result.nullableInt32Field_ = nullableInt32FieldBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum) {
          return mergeFrom((io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum other) {
        if (other == io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.getDefaultInstance()) return this;
        if (other.enumField_ != 0) {
          setEnumFieldValue(other.getEnumFieldValue());
        }
        if (!other.getStringField().isEmpty()) {
          stringField_ = other.stringField_;
          onChanged();
        }
        if (other.hasNullableInt32Field()) {
          mergeNullableInt32Field(other.getNullableInt32Field());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int enumField_ = 0;
      /**
       * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
       * @return The enum numeric value on the wire for enumField.
       */
      @java.lang.Override public int getEnumFieldValue() {
        return enumField_;
      }
      /**
       * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
       * @param value The enum numeric value on the wire for enumField to set.
       * @return This builder for chaining.
       */
      public Builder setEnumFieldValue(int value) {
        
        enumField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
       * @return The enumField.
       */
      @java.lang.Override
      public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType getEnumField() {
        @SuppressWarnings("deprecation")
        io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType result = io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.valueOf(enumField_);
        return result == null ? io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType.UNRECOGNIZED : result;
      }
      /**
       * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
       * @param value The enumField to set.
       * @return This builder for chaining.
       */
      public Builder setEnumField(io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum.EnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        enumField_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TestMessageWithEnum.EnumType enumField = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnumField() {
        
        enumField_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stringField_ = "";
      /**
       * <code>string stringField = 2;</code>
       * @return The stringField.
       */
      public java.lang.String getStringField() {
        java.lang.Object ref = stringField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringField = 2;</code>
       * @return The bytes for stringField.
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        java.lang.Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringField = 2;</code>
       * @param value The stringField to set.
       * @return This builder for chaining.
       */
      public Builder setStringField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringField() {
        
        stringField_ = getDefaultInstance().getStringField();
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 2;</code>
       * @param value The bytes for stringField to set.
       * @return This builder for chaining.
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringField_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Int32Value nullableInt32Field_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> nullableInt32FieldBuilder_;
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       * @return Whether the nullableInt32Field field is set.
       */
      public boolean hasNullableInt32Field() {
        return nullableInt32FieldBuilder_ != null || nullableInt32Field_ != null;
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       * @return The nullableInt32Field.
       */
      public com.google.protobuf.Int32Value getNullableInt32Field() {
        if (nullableInt32FieldBuilder_ == null) {
          return nullableInt32Field_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : nullableInt32Field_;
        } else {
          return nullableInt32FieldBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public Builder setNullableInt32Field(com.google.protobuf.Int32Value value) {
        if (nullableInt32FieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nullableInt32Field_ = value;
          onChanged();
        } else {
          nullableInt32FieldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public Builder setNullableInt32Field(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (nullableInt32FieldBuilder_ == null) {
          nullableInt32Field_ = builderForValue.build();
          onChanged();
        } else {
          nullableInt32FieldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public Builder mergeNullableInt32Field(com.google.protobuf.Int32Value value) {
        if (nullableInt32FieldBuilder_ == null) {
          if (nullableInt32Field_ != null) {
            nullableInt32Field_ =
              com.google.protobuf.Int32Value.newBuilder(nullableInt32Field_).mergeFrom(value).buildPartial();
          } else {
            nullableInt32Field_ = value;
          }
          onChanged();
        } else {
          nullableInt32FieldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public Builder clearNullableInt32Field() {
        if (nullableInt32FieldBuilder_ == null) {
          nullableInt32Field_ = null;
          onChanged();
        } else {
          nullableInt32Field_ = null;
          nullableInt32FieldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public com.google.protobuf.Int32Value.Builder getNullableInt32FieldBuilder() {
        
        onChanged();
        return getNullableInt32FieldFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getNullableInt32FieldOrBuilder() {
        if (nullableInt32FieldBuilder_ != null) {
          return nullableInt32FieldBuilder_.getMessageOrBuilder();
        } else {
          return nullableInt32Field_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : nullableInt32Field_;
        }
      }
      /**
       * <code>.google.protobuf.Int32Value nullableInt32Field = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getNullableInt32FieldFieldBuilder() {
        if (nullableInt32FieldBuilder_ == null) {
          nullableInt32FieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getNullableInt32Field(),
                  getParentForChildren(),
                  isClean());
          nullableInt32Field_ = null;
        }
        return nullableInt32FieldBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMessageWithEnum)
    }

    // @@protoc_insertion_point(class_scope:TestMessageWithEnum)
    private static final io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum();
    }

    public static io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMessageWithEnum>
        PARSER = new com.google.protobuf.AbstractParser<TestMessageWithEnum>() {
      @java.lang.Override
      public TestMessageWithEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessageWithEnum(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMessageWithEnum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessageWithEnum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.connect.protobuf.test.TestMessageWithEnumWrapper.TestMessageWithEnum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMessageWithEnum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMessageWithEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TestMessageWithEnum.proto\032 google/prot" +
      "obuf/descriptor.proto\032\036google/protobuf/w" +
      "rappers.proto\"\266\001\n\023TestMessageWithEnum\0220\n" +
      "\tenumField\030\001 \001(\0162\035.TestMessageWithEnum.E" +
      "numType\022\023\n\013stringField\030\002 \001(\t\0227\n\022nullable" +
      "Int32Field\030\003 \001(\0132\033.google.protobuf.Int32" +
      "Value\"\037\n\010EnumType\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\002B@" +
      "\n\"io.confluent.connect.protobuf.testB\032Te" +
      "stMessageWithEnumWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_TestMessageWithEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestMessageWithEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMessageWithEnum_descriptor,
        new java.lang.String[] { "EnumField", "StringField", "NullableInt32Field", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
